version: '3.8'

services:
  python-server:
    build:
      context: ../code/python/py-server
      dockerfile: ../../../docker/Dockerfile.python-server
    ports:
      - "9871:9871"
    volumes:
      - ../code/python/py-server:/app
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    env_file:
      - ../.env