version: '3.8'

services:
  aiserver:
    build:
      context: ../code/python/aiserver
      dockerfile: Dockerfile
    ports:
      - "9871:9871"
    volumes:
      - ../code/python/aiserver:/app
      - ../data:/data
      - ../:/system_src:rw  # Changed from :ro to :rw to allow write access
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
    env_file:
      - ../.env

  nginx:
    build:
      context: ../code/web
      dockerfile: Dockerfile
    ports:
      - "9870:9870"
    volumes:
      - ../code/web/www:/usr/share/nginx/html
      - ../code/web/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - aiserver