version: '3.8'

services:
  aiserver:
    build:
      context: ../code/python/aiserver
      dockerfile: Dockerfile
    ports:
      - "9871:9871"
    volumes:
      - ../code/python/aiserver:/app
      - ../data:/data
      - ../:/system_src:rw
      - ../data/huggingface_cache:/root/.cache/huggingface
      - ${EXTERNAL_SYSTEM_SRC:-/tmp/external_system_src}:/external_system_src:rw
    environment:
      - FLASK_ENV=development
      - PYTHONUNBUFFERED=1
      - EXTERNAL_SYSTEM_SRC=/external_system_src
    env_file:
      - ../.env

  nginx:
    build:
      context: ../code/web
      dockerfile: Dockerfile
    ports:
      - "9870:9870"
    volumes:
      - ../code/web/www:/usr/share/nginx/html
      - ../code/web/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - aiserver